/**
 * Aggregate interfaces for the event-sourced financial simulation system
 */

import type { Command, CommandResult } from "./commands.ts";
import type { FinancialEvent } from "./events.ts";

/**
 * Base aggregate interface
 */
export interface Aggregate {
  /** Unique identifier for this aggregate */
  id: string;
  /** Session this aggregate belongs to */
  sessionId: string;
  /** Current version (number of events applied) */
  version: number;
  /** Uncommitted events generated by commands */
  uncommittedEvents: FinancialEvent[];
}

/**
 * Financial aggregate root interface
 */
export interface FinancialAggregate extends Aggregate {
  /** Process a command and generate events */
  processCommand(command: Command): Promise<CommandResult>;
  
  /** Apply an event to update internal state */
  applyEvent(event: FinancialEvent): void;
  
  /** Get uncommitted events and clear them */
  getUncommittedEvents(): FinancialEvent[];
  
  /** Mark events as committed */
  markEventsAsCommitted(): void;
  
  /** Replay events to rebuild state */
  replayEvents(events: FinancialEvent[]): void;
}

/**
 * Aggregate repository interface
 */
export interface AggregateRepository<T extends Aggregate> {
  /** Get aggregate by ID, replaying events if needed */
  getById(aggregateId: string, sessionId: string): Promise<T>;
  
  /** Save aggregate (persist uncommitted events) */
  save(aggregate: T): Promise<void>;
  
  /** Create a new aggregate */
  create(sessionId: string): Promise<T>;
  
  /** Delete aggregate and all its events */
  delete(aggregateId: string, sessionId: string): Promise<void>;
}

/**
 * Command bus interface
 */
export interface CommandBus {
  /** Dispatch a command to appropriate handler */
  dispatch<T extends Command>(command: T): Promise<CommandResult>;
  
  /** Register a command handler */
  registerHandler<T extends Command>(
    commandType: string, 
    handler: (command: T) => Promise<CommandResult>
  ): void;
  
  /** Unregister a command handler */
  unregisterHandler(commandType: string): void;
}