/**
 * Command interfaces for the event-sourced financial simulation system
 */

import type {
  ParameterTransition,
  UserParameters,
} from "../../types/financial.ts";

/**
 * Base interface for all commands
 */
export interface Command {
  /** Unique identifier for this command */
  id: string;
  /** Type of command (discriminator) */
  type: string;
  /** Session this command belongs to */
  sessionId: string;
  /** When this command was issued */
  timestamp: Date;
  /** Command metadata */
  metadata?: CommandMetadata;
}

/**
 * Command metadata for traceability
 */
export interface CommandMetadata {
  /** User who issued this command */
  userId?: string;
  /** Correlation ID for tracking related commands */
  correlationId?: string;
  /** Additional context */
  context?: Record<string, any>;
}

/**
 * Command to run a complete financial simulation
 */
export interface RunSimulationCommand extends Command {
  type: "RunSimulation";
  data: {
    parameters: UserParameters;
    startDate: Date;
    endDate: Date;
    transitions?: ParameterTransition[];
  };
}

/**
 * Command to update financial parameters
 */
export interface UpdateParametersCommand extends Command {
  type: "UpdateParameters";
  data: {
    parameterChanges: Partial<UserParameters>;
    effectiveDate?: Date;
  };
}

/**
 * Command to process a single time step in the simulation
 */
export interface ProcessTimeStepCommand extends Command {
  type: "ProcessTimeStep";
  data: {
    currentDate: Date;
    interval: "week" | "fortnight" | "month" | "year";
    currentState: {
      cash: number;
      investments: number;
      superannuation: number;
      loanBalance: number;
      offsetBalance: number;
      netWorth: number;
      cashFlow: number;
      [key: string]: any;
    };
  };
}

/**
 * Command to add a parameter transition
 */
export interface AddParameterTransitionCommand extends Command {
  type: "AddParameterTransition";
  data: {
    transition: ParameterTransition;
  };
}

/**
 * Command to remove a parameter transition
 */
export interface RemoveParameterTransitionCommand extends Command {
  type: "RemoveParameterTransition";
  data: {
    transitionId: string;
  };
}

/**
 * Command to clear the event cache and restart simulation
 */
export interface ClearCacheCommand extends Command {
  type: "ClearCache";
  data: {
    reason?: string;
  };
}

/**
 * Command to run a comparison simulation
 */
export interface CompareScenariosCommand extends Command {
  type: "CompareScenarios";
  data: {
    configuration: import("../../types/financial.ts").SimulationConfiguration;
  };
}

/**
 * Union type of all possible commands
 */
export type AnyCommand =
  | RunSimulationCommand
  | UpdateParametersCommand
  | ProcessTimeStepCommand
  | AddParameterTransitionCommand
  | RemoveParameterTransitionCommand
  | ClearCacheCommand
  | CompareScenariosCommand;

/**
 * Command result interface
 */
export interface CommandResult {
  /** Whether the command was successful */
  success: boolean;
  /** Command that was processed */
  commandId: string;
  /** Events generated by this command */
  events: string[];
  /** Error message if command failed */
  error?: string;
  /** Additional result data */
  data?: Record<string, any>;
}

/**
 * Command handler interface
 */
export interface CommandHandler<T extends Command> {
  /** Handle the command and return result */
  handle(command: T): Promise<CommandResult>;
  /** Validate the command before processing */
  validate(command: T): Promise<boolean>;
}

/**
 * Command type registry
 */
export const COMMAND_TYPES = {
  RUN_SIMULATION: "RunSimulation",
  UPDATE_PARAMETERS: "UpdateParameters",
  PROCESS_TIME_STEP: "ProcessTimeStep",
  ADD_PARAMETER_TRANSITION: "AddParameterTransition",
  REMOVE_PARAMETER_TRANSITION: "RemoveParameterTransition",
  CLEAR_CACHE: "ClearCache",
  COMPARE_SCENARIOS: "CompareScenarios",
} as const;
