// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_quote from "./routes/api/quote.ts";
import * as $api_simulation_commands from "./routes/api/simulation/commands.ts";
import * as $api_simulation_index from "./routes/api/simulation/index.ts";
import * as $api_simulation_projections from "./routes/api/simulation/projections.ts";
import * as $api_simulation_session from "./routes/api/simulation/session.ts";
import * as $api_simulation_stats from "./routes/api/simulation/stats.ts";
import * as $api_simulation_websocket from "./routes/api/simulation/websocket.ts";
import * as $api_tax_config from "./routes/api/tax-config.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $help from "./routes/help.tsx";
import * as $index from "./routes/index.tsx";
import * as $test_input from "./routes/test-input.tsx";
import * as $test_simulation from "./routes/test-simulation.tsx";
import * as $test_visualization from "./routes/test-visualization.tsx";
import * as $ComparisonIsland from "./islands/ComparisonIsland.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $ExpenseManagerIsland from "./islands/ExpenseManagerIsland.tsx";
import * as $HousePurchaseIsland from "./islands/HousePurchaseIsland.tsx";
import * as $HouseholdManagerIsland from "./islands/HouseholdManagerIsland.tsx";
import * as $InputIsland from "./islands/InputIsland.tsx";
import * as $InvestmentManagerIsland from "./islands/InvestmentManagerIsland.tsx";
import * as $MainIsland from "./islands/MainIsland.tsx";
import * as $ScenarioManagerIsland from "./islands/ScenarioManagerIsland.tsx";
import * as $SettingsIsland from "./islands/SettingsIsland.tsx";
import * as $SimulationIsland from "./islands/SimulationIsland.tsx";
import * as $TransitionManagerIsland from "./islands/TransitionManagerIsland.tsx";
import * as $VisualizationIsland from "./islands/VisualizationIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/quote.ts": $api_quote,
    "./routes/api/simulation/commands.ts": $api_simulation_commands,
    "./routes/api/simulation/index.ts": $api_simulation_index,
    "./routes/api/simulation/projections.ts": $api_simulation_projections,
    "./routes/api/simulation/session.ts": $api_simulation_session,
    "./routes/api/simulation/stats.ts": $api_simulation_stats,
    "./routes/api/simulation/websocket.ts": $api_simulation_websocket,
    "./routes/api/tax-config.ts": $api_tax_config,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/help.tsx": $help,
    "./routes/index.tsx": $index,
    "./routes/test-input.tsx": $test_input,
    "./routes/test-simulation.tsx": $test_simulation,
    "./routes/test-visualization.tsx": $test_visualization,
  },
  islands: {
    "./islands/ComparisonIsland.tsx": $ComparisonIsland,
    "./islands/Counter.tsx": $Counter,
    "./islands/ExpenseManagerIsland.tsx": $ExpenseManagerIsland,
    "./islands/HousePurchaseIsland.tsx": $HousePurchaseIsland,
    "./islands/HouseholdManagerIsland.tsx": $HouseholdManagerIsland,
    "./islands/InputIsland.tsx": $InputIsland,
    "./islands/InvestmentManagerIsland.tsx": $InvestmentManagerIsland,
    "./islands/MainIsland.tsx": $MainIsland,
    "./islands/ScenarioManagerIsland.tsx": $ScenarioManagerIsland,
    "./islands/SettingsIsland.tsx": $SettingsIsland,
    "./islands/SimulationIsland.tsx": $SimulationIsland,
    "./islands/TransitionManagerIsland.tsx": $TransitionManagerIsland,
    "./islands/VisualizationIsland.tsx": $VisualizationIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
