/**
 * Template application utilities for parameter transitions
 * Provides functions to apply predefined templates to generate parameter changes
 */

import type {
  TransitionTemplate,
  UserParameters,
} from "../types/financial.ts";
import { TRANSITION_TEMPLATES } from "../types/financial.ts";

/**
 * Applies a transition template to generate parameter changes
 * 
 * @param templateId - The ID of the template to apply
 * @param currentParams - The current user parameters to base changes on
 * @returns Partial parameter changes generated by the template, or null if template not found
 * 
 * @example
 * ```typescript
 * const changes = applyTemplate("semi-retirement", currentParams);
 * if (changes) {
 *   // Use changes to create a new transition
 * }
 * ```
 */
export function applyTemplate(
  templateId: string,
  currentParams: UserParameters,
): Partial<UserParameters> | null {
  // Find the template by ID
  const template = TRANSITION_TEMPLATES.find((t) => t.id === templateId);

  if (!template) {
    return null;
  }

  // Generate parameter changes using the template's function
  return template.generateChanges(currentParams);
}

/**
 * Gets a template by its ID
 * 
 * @param templateId - The ID of the template to retrieve
 * @returns The template, or null if not found
 */
export function getTemplateById(
  templateId: string,
): TransitionTemplate | null {
  return TRANSITION_TEMPLATES.find((t) => t.id === templateId) || null;
}

/**
 * Gets all templates in a specific category
 * 
 * @param category - The category to filter by (e.g., "retirement", "career", "lifestyle")
 * @returns Array of templates in that category
 */
export function getTemplatesByCategory(
  category: string,
): TransitionTemplate[] {
  return TRANSITION_TEMPLATES.filter((t) => t.category === category);
}

/**
 * Gets all available template categories
 * 
 * @returns Array of unique category names
 */
export function getTemplateCategories(): string[] {
  const categories = new Set(TRANSITION_TEMPLATES.map((t) => t.category));
  return Array.from(categories);
}

/**
 * Gets all available templates
 * 
 * @returns Array of all transition templates
 */
export function getAllTemplates(): TransitionTemplate[] {
  return [...TRANSITION_TEMPLATES];
}
